#!/bin/bash

# submitted - rev1
#BASECOMMIT=df89f2550b5
# rev 1 - rev 2
# BASECOMMIT=c989a43644004
# rev 2 - rev 3
BASECOMMIT=8c256108be70

./git-latexdiff --bibtex --main paper2.tex --output paper2_diff.pdf $BASECOMMIT
